version: 1
formatters: {
  verbose: {
    format: '%(asctime)-15s %(name)-5s %(levelname)-8s %(message)s'
  }
}
handlers:
  console:
    class: logging.StreamHandler
    formatter: verbose
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: verbose
    filename: process.log
    maxBytes: 1048576
    backupCount: 3
    level: INFO
loggers:
  logger:
    handlers:
      - console
      - file
    level: DEBUG
